### ISSUE TITLE
Request for file removal: AcuminProExtraCondensed-Bold.otf

### ISSUE THREAD

**Issue by miguelsousa** [Sevas727/ReactTest1#1]
When using http://www.getthefont.com/, I found your font file [AcuminProExtraCondensed-Bold.otf](http://github.com/Sevas727/ReactTest1/blob/257fa192d7aa1a2aa9596a749b784bed8ddc41e4/client/styles/fonts/AcuminProExtraCondensed-Bold.otf), uploaded in this repository. I believe that this file was uploaded here by mistake, because its license does not allow distribution through a public website.

I would like to kindly ask you to remove this font file from the repository.

Kind regards,

**Comment by Sevas727** [comment]
I deleted the file that you asked, and updated this repo.
